### ISSUE TITLE
Kubernetes Pod를 외부에 노출하는 방법 (서비스)

### ISSUE THREAD

**Issue by zusdn90** [zusdn90/TIL-Develop-Issue#275]
[서비스]
- 파드의 논리적 집합과 그것들에 접근할 수 있는 정책을 정의하는 추상적 개념
- 왜 필요한가?
- 각 POD는 고유의 IP를 가지지만 내려갔다가 다시 올라오면 IP가 변경됨.
- 클러스터 내 POD들 간에 통신이 필요할 때 POD의 IP가 계속 바뀌므로 특정 POD를 대상으로 선정할 수가 없다.
- 또한 여러 Pod에 같은 애플리케이션을 운용할 경우 이 Pod 간의 로드밸런싱을 지원해줘야 하는데, 서비스가 이러한 역할을 한다.
- 서비스는 다음과 같이 구성이 가능하며, 라벨 셀렉터 (label selector)를 이용하여, 관리하고자 하는 Pod 들을 정의할 수 있다. 

```
apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
spec:
  selector:
    app: hello-node
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
```

- 서비스는 동시에 하나의 포트 뿐 아니라 여러개의 포트를 동시에 지원할 수 있다. 
- 예를 들어 웹서버의 HTTP와 HTTPS 포트가 대표적인 예인데,  아래와 같이 ports 부분에 두개의 포트 정보를 정의해주면 된다.

```
apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
spec:
  selector:
    app: hello-node
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8082
  type: LoadBalancer
```

- 서비스가 Pod들에 부하를 분산할때 디폴트 알고리즘은 Pod 간에 랜덤으로 부하를 분산하도록 한다. 
- 만약에 특정 클라이언트가 특정 Pod로 지속적으로 연결이 되게 하려면  Session Affinity를 사용하면 되는데, 서비스의 spec 부분에 sessionAffinity: ClientIP로 주면 된다.

![image](https://user-images.githubusercontent.com/15190903/204407786-80282616-fbd4-4ae8-a36e-266618be9a72.png)
- 웹에서 HTTP Session을 사용하는 경우와 같이 각 서버에 각 클라이언트의 상태정보가 저장되어 있는 경우에 유용하게 사용할 수 있다.

[인그레스]
- 클러스터 외부에서 클러스터 내부 서비스로 HTTP와 HTTPS 경로를 노출한다. 
- 트래픽 라우팅은 인그레스 리소스에 정의된 규칙에 의해 컨트롤 된다. 간단히 말하면 서비스들에 대한 라우터라고 보면 된다.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/15190903/190570311-bd0fa00d-94bd-4ecb-a4d6-733955e587e9.png">

<img width="693" alt="image" src="https://user-images.githubusercontent.com/15190903/190570353-e35c88b5-ffa1-408e-b275-ac03ccbf5bef.png">

[출처]
- https://bcho.tistory.com/1262
- https://medium.com/fenderi/kubernetes-pod-%EC%99%B8%EB%B6%80-%EB%85%B8%EC%B6%9C-%EB%B0%A9%EB%B2%95-gke-%ED%99%98%EA%B2%BD-514e2c2e56c7
