### ISSUE TITLE
Kubernetes 특정 node에 pod 배포 - label, nodeSelector, affinity(nodeAffinity, podAffinity)

### ISSUE THREAD

**Issue by zusdn90** [zusdn90/TIL-Develop-Issue#291]
- k8s클러스터에 pod배포 시  label, nodeSelector, affinity를 활용하여 특정 Node에 pod를 배포할 수 있다.

1. nodeSelector
- label을 기준으로 deployment에 nodeSelector를 추가

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-app-deployment
  labels:
    app: wildfly-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildfly-app
  template:
    metadata:
      labels:
        app: wildfly-app
    spec:
      containers:
      - name: wildfly-app
        image: 192.168.56.100:5000/middleware/wildfly/wildfly_custom_image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      **nodeSelector:
        key: worker**
```
위와 같이 deployment에 nodeSelector에 key, value를 지정하면 해당 label을 갖고 있는 node에만 배포가 진행된다.

2) affinity
- affinity는 뜻 그대로 유연한 Scheduling이 가능하도록 구성할 수 있습니다.
- 앞서 살펴본 nodeSelector의 경우 label naming을 기준으로 Pod를 특정 노드 또는 특정 노드 그룹에 배포하는 방식을 사용하였다면, 
- affinity는 다양한 조건을 제시할 수 있고 유연하게 처리할 수 있습니다.

[참고]
- https://waspro.tistory.com/582
