### ISSUE TITLE
Kubernetes Nginx ingress Controller

### ISSUE THREAD

**Issue by zusdn90** [zusdn90/TIL-Develop-Issue#293]
- Ingress는 클러스터 외부의 요청을 Ingress 리소스에 정의된 규칙에 따라 클러스터 내부의 서비스로 연결해준다.
- ingress-nginx는 NGINX를 reverse-proxy 및 로드 밸런서로 사용하는 Kubernetes용 Ingress 컨트롤이다.
- annotation설정으로 ssl/tls 인증서 적용, white-list관리, Canary배포, 요청에 대한 인증 등 여러가지 설정을 할 수 있다.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
```

[참고]
- https://kubernetes.io/docs/concepts/services-networking/ingress/
