### ISSUE TITLE
datahub keycloak 연동

### ISSUE THREAD

**Issue by zusdn90** [zusdn90/TIL-Develop-Issue#318]
1. datahub helm vaule.yml 업데이트

```
datahub-frontend:
  enabled: true
  image:
    repository: linkedin/datahub-frontend-react
    tag: "v0.9.0"
  # Set up ingress to expose react front-end
  ingress:
    enabled: false
  nodeSelector: { zone: cpu, nodetype: master, instancetype: ondemand }

  extraEnvs:
    - name: AUTH_OIDC_ENABLED
      value: "true"
    - name: AUTH_OIDC_CLIENT_ID
      value: "datahub"
    - name: AUTH_OIDC_CLIENT_SECRET
      value: "sdkxvncvowefksdk.efdf"
    - name: AUTH_OIDC_DISCOVERY_URI
      value: "https://yourdomain/auth/realms/your realm/.well-known/openid-configuration"
    - name: AUTH_OIDC_BASE_URL
      value: "https://datahub.test.com"
```

2. keycloak에서 client생성
<img width="363" alt="image" src="https://user-images.githubusercontent.com/15190903/211444941-38997391-35be-4b1e-95a9-cc57152486a4.png">

[참고]
- https://www.syscrest.com/2022/11/datahub-oidc-identity-group-managment-with-keycloak/
