### ISSUE TITLE
Keycloak HA Install on Kubernetes

### ISSUE THREAD

**Issue by zusdn90** [zusdn90/TIL-Develop-Issue#322]
- HA구성을 위해서 Keycloak은 여러 replica(replica > 1)으로 실행해야 합니다. 
- Chart에는 headless service를 기반으로 DNS 이름을 생성하는 헬퍼 템플릿(keycloak.serviceDnsName)이 있습니다.

- helm install keycloak codecentric/keycloak -n keycloak --set replicas=2

yaml파일의 아래 내용 추가
```
extraEnv: |
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: kubernetes.KUBE_PING
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: CACHE_OWNERS_COUNT
    value: "2"
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: "2"
```

[참고]
- https://github.com/codecentric/helm-charts/tree/master/charts/keycloak
